<a href="https://colab.research.google.com/github/ricadoarieljuradoatilano/Tareas-de-estocasticos-/blob/main/Ejercicios_actividad6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A continuacion se presentan los codigos de la actividad 6, por ricardo ariel jurado atilano


In [3]:
#codigo de chapman
import numpy as np
from math import exp, factorial, sqrt, ceil

R = np.array([
    [0, 2, 3, 0],
    [4, 0, 2, 0],
    [0, 2, 0, 2],
    [1, 0, 3, 0]
], dtype=float)

ri = np.sum(R, axis=1)
r = np.max(ri)

n = len(R)

P_hat = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        if i == j:
            P_hat[i, j] = 1 - ri[i] / r
        else:
            P_hat[i, j] = R[i, j] / r

print("r =", r)
print("\nP_hat =")
print(P_hat)

def P_t(t):

    M = int(ceil(max(r*t + 5*sqrt(r*t), 20)))

    P = np.zeros((n, n))

    for k in range(M + 1):

        coef = exp(-r*t) * (r*t)**k / factorial(k)

        P += coef * np.linalg.matrix_power(P_hat, k)

    return P, M

for t in [0.5, 1, 5]:

    P, M = P_t(t)

    print("\n-----------------------------------")
    print("t =", t)
    print("M =", M)
    print(np.round(P, 6))

P05, _ = P_t(0.5)
P1, _ = P_t(1)

error = np.max(np.abs(P1 - P05 @ P05))

print("\nError Chapman-Kolmogorov:")
print(error)

r = 6.0

P_hat =
[[0.16666667 0.33333333 0.5        0.        ]
 [0.66666667 0.         0.33333333 0.        ]
 [0.         0.33333333 0.33333333 0.33333333]
 [0.16666667 0.         0.5        0.33333333]]

-----------------------------------
t = 0.5
M = 20
[[0.250609 0.216965 0.386657 0.14577 ]
 [0.253135 0.238361 0.374409 0.134095]
 [0.169119 0.193615 0.420301 0.216965]
 [0.158017 0.157445 0.398332 0.286206]]

-----------------------------------
t = 1
M = 20
[[0.206151 0.203902 0.39871  0.191236]
 [0.208284 0.205341 0.397899 0.188474]
 [0.196758 0.198379 0.400959 0.203902]
 [0.192046 0.193997 0.401471 0.212484]]

-----------------------------------
t = 5
M = 58
[[0.2      0.2      0.399999 0.2     ]
 [0.2      0.2      0.399999 0.2     ]
 [0.2      0.2      0.399999 0.2     ]
 [0.2      0.2      0.399999 0.2     ]]

Error Chapman-Kolmogorov:
5.820333639494635e-07


In [4]:
#uniformizadion codigo
import numpy as np
from math import exp

R = np.array([
    [0, 2, 3, 0],
    [4, 0, 2, 0],
    [0, 2, 0, 2],
    [1, 0, 3, 0]
], dtype=float)

ri = np.sum(R, axis=1)
r = np.max(ri)

n = len(R)

P_hat = np.zeros((n, n))

for i in range(n):
    for j in range(n):

        if i == j:
            P_hat[i, j] = 1 - ri[i] / r
        else:
            P_hat[i, j] = R[i, j] / r

def uniformizacion(t, epsilon=1e-5):

    A = np.eye(n)

    B = exp(-r*t) * np.eye(n)

    c = exp(-r*t)

    suma = c

    k = 1

    while suma < 1 - epsilon:

        c = c * (r*t) / k

        B = B + c*A

        A = A @ P_hat

        suma = suma + c

        k += 1

    M = k - 1

    return B, M

for t in [0.5, 1, 5]:

    P, M = uniformizacion(t)

    print("\n------------------------------------")
    print("t =", t)
    print("M =", M)
    print(np.round(P, 6))


------------------------------------
t = 0.5
M = 13
[[0.366336 0.196353 0.334342 0.102965]
 [0.254733 0.342981 0.310987 0.091296]
 [0.126304 0.173014 0.504326 0.196353]
 [0.12632  0.114634 0.346012 0.41303 ]]

------------------------------------
t = 1
M = 19
[[0.220086 0.206203 0.394096 0.179609]
 [0.217758 0.216815 0.390825 0.174596]
 [0.189635 0.196177 0.407979 0.206203]
 [0.18288  0.184622 0.399109 0.233384]]

------------------------------------
t = 5
M = 56
[[0.199999 0.199999 0.399997 0.199999]
 [0.199999 0.199999 0.399997 0.199999]
 [0.199999 0.199999 0.399997 0.199999]
 [0.199999 0.199999 0.399997 0.199999]]
